### ISSUE TITLE
One undefined attribute in your model

### ISSUE THREAD

**Issue by Jiaoma** [tansor/VecRoad#1]
Hi, thank you for your code sharing. When I ran your inference code, I found that in your DecoderBlock, you use an attribute called cat_ch, which is not defined. It may be a small mistake.
The output is as below.
`initializing model
Traceback (most recent call last):
  File "infer.py", line 554, in <module>
    main()
  File "infer.py", line 54, in main
    net = prepare_net().eval()
  File "infer.py", line 430, in prepare_net
    net = RPNet(cfg.TRAIN.NUM_TARGETS)
  File "/home/molijuly/github/VecRoad/model/model.py", line 154, in __init__
    DecoderBlock(self.ft_chs[0], 32),
  File "/home/molijuly/github/VecRoad/model/model.py", line 39, in __init__
    ConvReLU(self.cat_ch, self.res_ch, 3),
  File "/home/molijuly/anaconda3/envs/pt10py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'DecoderBlock' object has no attribute 'cat_ch'
`

**Comment by Jiaoma** [comment]
By the way, the script graphs2seg.py mentioned in "Evaluation-Pixel Metric" did not give pixel metric scores. Could you also share the evaluating script that directly calculates the P-F1 scores in your article?

**Comment by tansor** [comment]
Thanks for your bug report. It has been fixed now. 
The script used to evaluate P-F1 could be found at [ssai-cnn's scripts/evaluate_single.py](https://github.com/mitmul/ssai-cnn/blob/master/scripts/evaluate_single.py) with a little change. I will consider to add it directly into this repo in the next few updates.
Let me know if I have solved your confusion.

**Comment by Jiaoma** [comment]
Thanks for your reply. I'm still working on reimplementing the training code of your work. It could be much helpful for the following researchers if you could reconsider releasing your training code 😂

**Comment by tansor** [comment]
P-F1 codes have been updated in /eval/eval_pixel_metrics.py.
Masks of test regions have been uploaded in the OSM dataset Baidu Netdisk link.
Done.
