### ISSUE TITLE
there is a question when I run the file infer.py

### ISSUE THREAD

**Issue by angleyun** [tansor/VecRoad#3]
![2020-10-13 17-33-58屏幕截图](https://user-images.githubusercontent.com/24848689/95844096-12a6ec80-0d7b-11eb-9f24-c77b2d25e075.png)
First of all, I am very grateful that you have open sourced the code. Here I have a small question to ask you whether there is an array overflow when the file--infer.py is interrupted here.
My GPU memory is 24G, and the virtual environment is configured according to your instructions. Waiting for your answer, thank you very much.

**Comment by tansor** [comment]
Hi, angleyun, let me know if you have an OOM(out of memory) error?
`htop` would monitor the memory usage timely.
If so, try infer only one region at a time.
P.S. 64GB memory (not the GPU memory but the CPU memory) is used in my environment.

**Comment by angleyun** [comment]
Thank you for your reply. It's really a memory problem. Thank you very much.  I'm sorry that I didn't see the message before.  I would like to express my sincere thanks
