### ISSUE TITLE
Questions about the infer code

### ISSUE THREAD

**Issue by neiheih** [tansor/VecRoad#6]
Hi, thank you for sharing the code.  I'm using it to do my research. I have a few questions about it.
1. What's the meaning of the param is_key_point in the "push" method in model_utils.py and how to set it?
2. How does "proc" method work in the "push" method?
I'm appreciated if you could add more annotations to this piece of code.

**Comment by tansor** [comment]
1. `is_key_point` is used to determine the number of time steps of output points that will be added to the graph. If `is_key_point==True`, it means that the point of this time step is a junction.
2. `proc` function is used to add points of one timestep to the graph.
